default: &default
  adapter: postgresql
  encoding: unicode
  username: gamou
  password: gamou
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gamou_development

test:
  <<: *default
  database: gamou_test

production:
  <<: *default
  database: gamou_production
  username: gamou
  password: gamou
